name: Build and deploy Next.js (standalone) to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          # 必須3点セット
          cp -r .next/standalone deploy/
          cp -r .next/static deploy/.next/static
          if [ -d public ]; then cp -r public deploy/public; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-standalone
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: next-standalone
          path: .

      - name: Zip
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima30'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B47337E9A3FD479480DDAF997372638B }}
          package: app.zip
