name: Build and deploy Next.js (standalone) to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static
          cp -r .next/standalone/* deploy/
          cp -r public deploy/public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: .

      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "YOUR_AZURE_APP_NAME"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
