name: Build and deploy Next.js (prebuilt)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # 本番実行に不要な devDependencies を削る
      - name: Prune devDependencies
        run: npm prune --production

      # 実行に必要なものだけまとめる
      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -r .next deploy/.next
          if [ -d public ]; then cp -r public deploy/public; fi
          cp package.json deploy/package.json
          cp -r node_modules deploy/node_modules
          if [ -f next.config.js ]; then cp next.config.js deploy/next.config.js; fi

      - name: Zip artifact
        run: |
          cd deploy
          zip -r ../app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-002-gen10-step3-1-node-oshima30
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B47337E9A3FD479480DDAF997372638B }}
          package: app.zip
