name: Build and deploy Next.js (standalone) to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build

      - name: Prepare deploy folder
        run: |
          set -eux
          rm -rf deploy
          mkdir -p deploy
          # standalone 一式を deploy/ にコピー
          cp -r .next/standalone/* deploy/
          # 静的ファイル
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static
          # public があれば同梱
          if [ -d public ]; then cp -r public deploy/public; fi
          # 起動用の最小 package.json（npm start を node server.js に固定）
          cat > deploy/package.json << 'JSON'
          {
            "name": "next-standalone",
            "version": "1.0.0",
            "private": true,
            "scripts": {
              "start": "node server.js"
            },
            "engines": {
              "node": ">=22.x"
            }
          }
          JSON

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-standalone
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-standalone
          path: .

      - name: Zip for Azure
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima30' # ←あなたの Web App 名
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B47337E9A3FD479480DDAF997372638B }}
          package: app.zip
